### ISSUE TITLE
Batch add doesn't work on large folder

### ISSUE THREAD

**Issue by SaotomeRanma142** [Blasbothewise/hgame-selector#8]
Pointed batch add to a folder with 607 games in it. Scan completes successfully but when I press the add H games button at the bottom, nothing happens.

**Comment by Blasbothewise** [comment]
Apologies for getting back so late, I only noticed your issue just now.

To clarify:

No error was thrown?
Restarting the app doesn't show any items in you collection i(.e. if it may have saved but failed to react gui wise)?
If you could try again and show me the output dev tools console output by going to View > Toggle developer tools.

In the meantime I'll attempt to add my entire collection in one go to see if I can replicate.

**Comment by Blasbothewise** [comment]
Well I found one bug so far which involved the batch submission failing if it encounters a single hgame that doesn't have tags.

**Comment by Blasbothewise** [comment]
I've not been able to find any errors other than that from submitting my collection.
Did take a while (roughly a min and a half) to add everything though, though thats understandable when submitting so many.

Could you try adding your collection via this build and letting me know if it works?
https://github.com/Blasbothewise/hgame-selector/releases/tag/1.4.1

**Comment by SaotomeRanma142** [comment]
![Capture](https://user-images.githubusercontent.com/16344732/129446720-c3f21a9c-9697-4e24-87e8-a7b02b55ce77.PNG)

Well, now it throws the attached error after about 30 seconds or so.

**Comment by Blasbothewise** [comment]
The error in your screenshot is telling me one of those file locations/files doesn't exist.
From checking the game on dlsite I can see the name's icon has a forward slash in it, which in the rename for storage process has been converted to a backslash.
It's essentially trying to find the folder "grouping huge tits train-our courage" which doesn't exist.
In hindsight there's really no need for me to rename the image file so I'm going to revert to just having the dlsite code as the icon name.

>551
You're indeed right.
There can be a couple reasons for this.
Batch add is best effort searching for EXEs and dlsite codes only atm.
A hgame won't be detected if it doesn't contain any EXEs, a Dlsite code in it's file path and if it doesn't have a dlsite webpage (i.e. if a circle took down a product, I have a couple like this I had to add manually).

**Comment by Blasbothewise** [comment]
This build should fix the icon error, let me know if it works:
https://github.com/Blasbothewise/hgame-selector/releases/tag/1.4.2

Regarding the hgames that aren't detected.
I'd appreciate it if you could give me a couple examples of those that don't show up so I can get a better insight into what I need to support.

For my collection I know I need to support swf and html files for some of my games.

**Comment by SaotomeRanma142** [comment]
Every game in the folder has an exe and has the RJ code in the folder name. I will check this build to see if it manages to import the 551 detected games and if so, find you an example or two. All of them are detected by DLSite Game Manager which is what I currently use. I have been looking for an alternative as newer versions of that have malware.

**Comment by SaotomeRanma142** [comment]
It worked. Here is the path of one that was missed:

H:\DLSITE\MANAGED\RE201109_[Toro Toro Resistance]_ +Monmusu Quest! Paradox RPG [Part Two]\Game.exe

**Comment by Blasbothewise** [comment]
Ah okay, from replicating your scenario I've found it was a flaw with how I detect dlsite codes.
I've replaced said matching method with a much more robust custom regex solution.

Here's the build amending such:
https://github.com/Blasbothewise/hgame-selector/releases/tag/1.4.3

**Comment by SaotomeRanma142** [comment]
That made a difference, 589 were found. Attached is the directory listing if that would help nail down the rest of them.

[paths.txt](https://github.com/Blasbothewise/hgame-selector/files/6987219/paths.txt)

**Comment by Blasbothewise** [comment]
Well I wrote a script for checking which have dlsite pages and these codes no longer have product pages:

RJ031690
RJ039393
RJ054058
RJ152222
RJ182019
RJ200200
RJ256661
RJ273487
RJ095871
RJ180718
RJ184888
RJ184888
RJ234198

"RJ50158_[ぬるポン]_お姉ちゃんポンポン", is missing a "0" at the start, hence why that one doesn't show up.

So that's at least 14 which aren't the app's fault per say.

**Comment by SaotomeRanma142** [comment]
I'll go ahead and close this now, looks like you pretty much took care of the problem. Those I will just have to add manually.

Thanks.
